Update introxt_arp

diff --git a/introxt_arp b/introxt_arp
--- a/introxt_arp
+++ b/introxt_arp
@@ -1,45 +1,36 @@
 #!/bin/bash
+
+# Clear the screen
 clear
-cd Logo && ./introxt_logo
-cd ..
-echo "Enter The Interface";
-read int;
-echo "Enter Your Ip Address";
-read ip;
-echo "Enter The Range From";
-echo "........:";read a ;echo ".";
-echo "....:"; read b ;echo ".";
-echo "..:"; read c ;echo ".";
-echo ".:"; read d ;echo ".";
-echo "Upto "
-echo "........:"; read a1 ;echo ".";
-echo "....:"; read b1 ;echo ".";
-echo "..:"; read c1 ;echo ".";
-echo ".:"; read d1 ;echo ".";
-echo $int > alive_host.txt;
-echo $int > arping.txt;
-i=0
-j=0
-k=0
-l=0
-m=0
-for ((i=a;i<=a1;i++))
-do 
-      for ((j=b;j<=b1;j++))
-          do  
-             for ((k=c;k<=c1;k++))
-                  do  
-                      for ((l=d;l<=d1;l++))
-                           do   
-                                arping -I $int -c 4 -s $ip $i.$j.$k.$l >> arping.txt
-                                if [ $? -eq 0 ]; then
-                                    echo $i.$j.$k.$l;
-                                   arp $i.$j.$k.$l  >> alive_host.txt;
-                                 fi 
-                                  
-                           done
-                 done
-         done
+
+# Optionally display the Introxt logo (if available)
+[ -d Logo ] && [ -x Logo/introxt_logo ] && cd Logo && ./introxt_logo && cd ..
+
+# Gather user input
+read -p "Enter the interface: " int
+read -p "Enter your IP address: " ip
+read -p "Enter the starting IP address (e.g., 192.168.1.1): " start_ip
+read -p "Enter the ending IP address: " end_ip
+
+# Validate IP addresses
+if [[ ! $start_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ || ! $end_ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    echo "Invalid IP address format."
+    exit 1
+fi
+
+# Prepare output files
+echo $int > alive_hosts.txt
+echo $int > arping.txt
+
+# Efficiently iterate through IP addresses
+for ipaddr in $(seq $start_ip $end_ip); do
+    arping -I $int -c 4 -s $ip $ipaddr >> arping.txt
+    if [ $? -eq 0 ]; then
+        echo $ipaddr
+        arp $ipaddr >> alive_hosts.txt
+    fi
 done
-cat alive_host.txt;
-echo "Thats All";
+
+# Display results
+cat alive_hosts.txt
+echo "Scan complete."
